### PR TITLE
Bash can add to a string

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by dingo-d** [comment]
I didn't get a notification about this one. I've copied this from the original action, this would add the options to a single line instead of multiple calls or?

**Comment by szepeviktor** [comment]
@dingo-d Greg's gone advanced since then: https://github.com/php-actions/phpstan/blob/master/entrypoint
Please consider doing that :)

**Comment by dingo-d** [comment]
I can add this, but since you've made the advancement in the original repo I'd love it if you'd do the same here 😄  

I wonder if I can cherry-pick that from the original repo so that you don't have to do much 🤔

**Comment by szepeviktor** [comment]
> I wonder if I can cherry-pick that from the original repo so that you don't have to do much 🤔

Good idea!

**Comment by dingo-d** [comment]
I'll merge this and cherry-pick the one you mentioned 💪

**Review by dingo-d — APPROVED** [review]

**Pull request merged**
